# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- devops

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'Run a one-line script'

- script: |
    ls -la
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'S2sStage-Registry'
    repository: 'front-stage'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'S2s-Service'
    appType: 'webAppContainer'
    WebAppName: 'front-stage'
    DockerNamespace: 'S2sStage'
    DockerRepository: 'front-stage'
    DockerImageTag: 'latest'



