# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  - develop
  - main

pr:
  - develop
  - main


stages:
  - stage: S2s
    displayName: S2s
    jobs: 
      - job: Deploy
        pool:
         vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'S2sStage-Registry'
            repository: 'front-stage'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'S2s-Service'
            appType: 'webAppContainer'
            WebAppName: 'front-stage'
            DockerNamespace: 'S2sStage'
            DockerRepository: 'front-stage'
            DockerImageTag: 'latest'



