trigger:
  - develop
  - devops
  - main

pr:
  - develop
  - devops
  - main
  
variables:
  agentOS: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and push docker image
    jobs: 
      - job: Build
        pool:
         vmImage: $(agentOS)
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'S2sStage-Registry'
            repository: 'front-stage'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'

        

  - stage: deploy
    jobs:
      - deployment: DeployCore
        displayName: Deploy image to app service
        environment: 'prod'
      - job: Deploy
        pool:
          vmImage: $(agentOS)
          strategy:
          runOnce:
            deploy:
              steps:
              - download: none
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'S2s-Service'
                  appType: 'webAppContainer'
                  WebAppName: 'front-stage'
                  DockerNamespace: 'S2sStage'
                  DockerRepository: 'front-stage'
                  DockerImageTag: '$(Build.BuildId)'


